// Biblioteca de leis — Edital SAEB 02/2026 · Investigador PC-BA
// Alertas podem conter <b> (renderizados com dangerouslySetInnerHTML).

export interface Lei {
  id: string
  n: string        // número do diploma
  nome: string
  m: string        // chave da matéria
  em: string       // ementa
  esc: string      // o que o edital cobra
  al: string[]     // alertas de atualização
  lk: string       // link oficial
}

export const MATERIAS = [
  { k: 'penal', t: 'Direito Penal' },
  { k: 'proc', t: 'Direito Processual Penal' },
  { k: 'extrav', t: 'Legislação Penal e Processual Extravagante' },
  { k: 'adm', t: 'Direito Administrativo' },
  { k: 'const', t: 'Direito Constitucional' },
  { k: 'geral', t: 'Legislação Geral e Estadual da Bahia' },
  { k: 'igual', t: 'Promoção da Igualdade Racial e de Gênero' },
] as const

export const LEIS: Lei[] = [
  /* ===== CÓDIGOS ===== */
  { id: 'cf88', n: 'CF/1988', nome: 'Constituição da República Federativa do Brasil', m: 'const',
    em: 'Norma fundamental do ordenamento jurídico brasileiro.',
    esc: 'Art. 5º integral; arts. 12 a 17 (nacionalidade e direitos políticos); arts. 18 a 24 (organização do Estado); arts. 37 a 41 (Administração Pública e servidores); arts. 136 a 141 (defesa do Estado); art. 144 integral (segurança pública). Para Igualdade Racial, também os arts. 1º, 3º e 4º.',
    al: ['O art. 144 recebeu as polícias penais pela EC 104/2019 — confira o inciso VI e os §§ correspondentes.'],
    lk: 'https://www.planalto.gov.br/ccivil_03/constituicao/constituicao.htm' },
  { id: 'cp', n: 'DL 2.848/1940', nome: 'Código Penal', m: 'penal',
    em: 'Institui o Código Penal brasileiro.',
    esc: 'Parte Geral integral (arts. 1º a 120). Da Parte Especial: crimes contra a pessoa (121 a 154-B), contra o patrimônio (155 a 183), contra a dignidade sexual (213 a 218-C e 234-A), contra a incolumidade pública (250 a 259 e 267 a 285), contra a paz pública (286 a 288-A), contra a fé pública (289 a 311-A), contra a Administração Pública (312 a 359-H) e contra o Estado Democrático de Direito (359-I a 359-T).',
    al: ['<b>Lei 14.994/2024:</b> criou o art. 121-A (feminicídio como crime autônomo, reclusão de 20 a 40 anos) e <b>revogou</b> o inciso VI do §2º e os §§2º-A e 7º do art. 121. O feminicídio deixou de ser qualificadora do homicídio.',
      '<b>Lei 14.532/2023:</b> revogou o §3º do art. 140 — a injúria racial migrou para o art. 2º-A da Lei 7.716/1989.',
      '<b>Lei 15.280/2025:</b> alterou o art. 217-A e criou o art. 338-A (descumprimento de medida protetiva, reclusão de 2 a 5 anos e multa).',
      '<b>Lei 15.358/2026:</b> alterou os arts. 91, 91-A, 92, 121 (§2º-D), 129 (§§3º-A e 8º-A), 147-C, 148 (§3º), 155 (§9º), 157, 158, 159 e 180, <b>revogando o §5º do art. 180</b> — extinta a receptação privilegiada.',
      '<b>Lei 15.159/2025:</b> majorantes para crimes em instituição de ensino (art. 121, §2º, X, e art. 129, §12).',
      '<b>Lei 15.123/2025:</b> parágrafo único do art. 147-B, com aumento pelo uso de inteligência artificial.'],
    lk: 'https://www.planalto.gov.br/ccivil_03/decreto-lei/del2848compilado.htm' },
  { id: 'cpp', n: 'DL 3.689/1941', nome: 'Código de Processo Penal', m: 'proc',
    em: 'Institui o Código de Processo Penal.',
    esc: 'Arts. 1º a 3º-F (disposições preliminares e juiz das garantias); 4º a 23 (inquérito policial); 24 a 62 (ação penal, com os arts. 28 e 28-A); 69 a 91 (competência); 92 a 154 (questões e processos incidentes); 155 a 250 (prova, incluindo cadeia de custódia 158-A a 158-F, reconhecimento 226 e busca e apreensão 240 a 250); 282 a 350 (prisão e medidas cautelares); 563 a 573 (nulidades).',
    al: ['<b>Juiz das garantias:</b> o STF, nas ADIs 6298, 6299, 6300 e 6305 (julgamento concluído em 24/08/2023), declarou <b>constitucionais</b> os arts. 3º-A a 3º-F, com interpretação conforme: a competência cessa com o oferecimento da denúncia e não se aplica a competência originária de tribunais, Tribunal do Júri, violência doméstica e infrações de menor potencial ofensivo. Declarou <b>inconstitucional</b> o parágrafo único do art. 3º-D e o §5º do art. 157.',
      '<b>Lei 15.358/2026:</b> inseriu o inciso V no art. 313 — fundamento autônomo de prisão preventiva para integrante de organização criminosa ultraviolenta.'],
    lk: 'https://www.planalto.gov.br/ccivil_03/decreto-lei/del3689compilado.htm' },

  /* ===== LEGISLAÇÃO PENAL E PROCESSUAL EXTRAVAGANTE ===== */
  { id: 'l5553', n: 'Lei 5.553/1968', nome: 'Apresentação e uso de documentos de identificação pessoal', m: 'extrav',
    em: 'Veda a retenção de documento de identificação pessoal.',
    esc: 'Texto integral — diploma curto, com cerca de sete artigos.', al: [],
    lk: 'https://www.planalto.gov.br/ccivil_03/leis/l5553.htm' },
  { id: 'l13869', n: 'Lei 13.869/2019', nome: 'Lei de Abuso de Autoridade', m: 'extrav',
    em: 'Dispõe sobre os crimes de abuso de autoridade praticados por agente público.',
    esc: 'Texto integral. Atenção especial aos arts. 9º, 10, 12, 13, 15, 22, 25, 28, 30, 32 e 33.',
    al: ['O art. 1º, §1º, exige <b>elemento subjetivo especial</b>: finalidade de prejudicar outrem, beneficiar a si ou a terceiro, ou por mero capricho ou satisfação pessoal.',
      'O §2º do art. 1º afasta o crime quando houver mera divergência na interpretação da lei ou na avaliação de fatos e provas.',
      'O art. 38 foi vetado.'],
    lk: 'https://www.planalto.gov.br/ccivil_03/_ato2019-2022/2019/lei/l13869.htm' },
  { id: 'l7716', n: 'Lei 7.716/1989', nome: 'Crimes de preconceito de raça, cor, etnia, religião ou procedência nacional', m: 'igual',
    em: 'Define os crimes resultantes de preconceito de raça ou de cor.',
    esc: 'Texto integral, na redação da Lei 14.532/2023.',
    al: ['<b>Lei 14.532/2023:</b> inseriu o <b>art. 2º-A</b>, tipificando a injúria racial como crime de racismo (reclusão de 2 a 5 anos e multa), imprescritível e inafiançável, com ação penal pública incondicionada. Criou ainda majorantes para racismo em contexto recreativo, esportivo, artístico, religioso e praticado por funcionário público.'],
    lk: 'https://www.planalto.gov.br/ccivil_03/leis/l7716.htm' },
  { id: 'l8072', n: 'Lei 8.072/1990', nome: 'Lei dos Crimes Hediondos', m: 'extrav',
    em: 'Dispõe sobre os crimes hediondos, nos termos do art. 5º, XLIII, da CF.',
    esc: 'Texto integral.',
    al: ['<b>Lei 14.994/2024:</b> incluiu o feminicídio no rol do art. 1º.',
      '<b>Lei 15.358/2026:</b> promoveu alteração pontual — confira a redação vigente.'],
    lk: 'https://www.planalto.gov.br/ccivil_03/leis/l8072.htm' },
  { id: 'l9503', n: 'Lei 9.503/1997', nome: 'Código de Trânsito Brasileiro — crimes de trânsito', m: 'extrav',
    em: 'Institui o Código de Trânsito Brasileiro.',
    esc: "Somente o Capítulo XIX, 'Dos Crimes de Trânsito' — arts. 291 a 312-B.", al: [],
    lk: 'https://www.planalto.gov.br/ccivil_03/leis/l9503compilado.htm' },
  { id: 'l9455', n: 'Lei 9.455/1997', nome: 'Lei de Tortura', m: 'extrav',
    em: 'Define os crimes de tortura.',
    esc: 'Texto integral — diploma curto.', al: [],
    lk: 'https://www.planalto.gov.br/ccivil_03/leis/l9455.htm' },
  { id: 'l9605', n: 'Lei 9.605/1998', nome: 'Lei de Crimes Ambientais', m: 'extrav',
    em: 'Sanções penais e administrativas derivadas de condutas lesivas ao meio ambiente.',
    esc: 'Texto integral. Destaque para os arts. 2º, 3º, 27, 28, 29, 32, 33, 40, 48, 54 e 60.',
    al: ['O STF dispensou a exigência de dupla imputação para a responsabilização penal da pessoa jurídica.'],
    lk: 'https://www.planalto.gov.br/ccivil_03/leis/l9605.htm' },
  { id: 'l10826', n: 'Lei 10.826/2003', nome: 'Estatuto do Desarmamento', m: 'extrav',
    em: 'Dispõe sobre registro, posse e comercialização de armas de fogo e munição.',
    esc: 'Texto integral. Destaque para os arts. 12 a 21.',
    al: ['<b>Lei 15.358/2026:</b> alterou dispositivos — confira a redação vigente.'],
    lk: 'https://www.planalto.gov.br/ccivil_03/leis/2003/l10.826.htm' },
  { id: 'l11340', n: 'Lei 11.340/2006', nome: 'Lei Maria da Penha', m: 'extrav',
    em: 'Cria mecanismos para coibir a violência doméstica e familiar contra a mulher.',
    esc: 'Texto integral.',
    al: ['<b>Lei 14.550/2023:</b> as medidas protetivas de urgência passaram a ser autônomas, com prazo indeterminado, independentes de inquérito ou processo (art. 19, §§).',
      '<b>Lei 14.994/2024:</b> a pena do art. 24-A (descumprimento de medida protetiva) passou a reclusão de 2 a 5 anos e multa.',
      '<b>Lei 15.125/2025:</b> monitoração eletrônica do agressor como medida autônoma (art. 22, §5º).',
      '<b>Lei 14.857/2024:</b> sigilo do nome da ofendida.'],
    lk: 'https://www.planalto.gov.br/ccivil_03/_ato2004-2006/2006/lei/l11340.htm' },
  { id: 'l11343', n: 'Lei 11.343/2006', nome: 'Lei de Drogas', m: 'extrav',
    em: 'Institui o Sistema Nacional de Políticas Públicas sobre Drogas.',
    esc: 'Texto integral. Destaque para os arts. 28, 33, 33 §4º, 34, 35, 40, 44, 48, 50 a 53.',
    al: ['<b>STF, Tema 506 (RE 635.659, julgamento concluído em 26/06/2024):</b> presume-se usuário quem porta até <b>40 gramas</b> de cannabis sativa ou seis plantas fêmeas. A presunção é <b>relativa</b>, podendo ser afastada por decisão fundamentada.',
      '<b>Lei 15.358/2026:</b> alterou dispositivos — confira a redação vigente.'],
    lk: 'https://www.planalto.gov.br/ccivil_03/_ato2004-2006/2006/lei/l11343.htm' },
  { id: 'l7960', n: 'Lei 7.960/1989', nome: 'Lei da Prisão Temporária', m: 'proc',
    em: 'Dispõe sobre prisão temporária.',
    esc: 'Texto integral — diploma curto.',
    al: ['O STF, na ADI 4.109, fixou que os requisitos do art. 1º devem ser lidos de forma <b>cumulativa</b>: imprescindibilidade para a investigação, ausência de identificação ou residência fixa e fundadas razões de autoria em crime do rol.'],
    lk: 'https://www.planalto.gov.br/ccivil_03/leis/l7960.htm' },
  { id: 'l9099', n: 'Lei 9.099/1995', nome: 'Juizados Especiais Cíveis e Criminais', m: 'proc',
    em: 'Dispõe sobre os Juizados Especiais Cíveis e Criminais.',
    esc: 'Capítulo III — parte criminal, arts. 60 a 92.',
    al: ['O art. 41 da Lei Maria da Penha veda a aplicação da Lei 9.099 aos crimes praticados com violência doméstica e familiar contra a mulher.'],
    lk: 'https://www.planalto.gov.br/ccivil_03/leis/l9099.htm' },
  { id: 'l10259', n: 'Lei 10.259/2001', nome: 'Juizados Especiais Federais', m: 'proc',
    em: 'Dispõe sobre os Juizados Especiais no âmbito da Justiça Federal.',
    esc: 'Texto integral. Destaque para os arts. 2º e 20.', al: [],
    lk: 'https://www.planalto.gov.br/ccivil_03/leis/2001/l10259.htm' },
  { id: 'l9296', n: 'Lei 9.296/1996', nome: 'Interceptação de comunicações telefônicas', m: 'proc',
    em: 'Regulamenta o art. 5º, XII, parte final, da Constituição Federal.',
    esc: 'Texto integral — diploma curto.', al: [],
    lk: 'https://www.planalto.gov.br/ccivil_03/leis/l9296.htm' },
  { id: 'l12850', n: 'Lei 12.850/2013', nome: 'Lei das Organizações Criminosas', m: 'extrav',
    em: 'Define organização criminosa e dispõe sobre a investigação criminal.',
    esc: 'Texto integral. Destaque para os arts. 1º, 2º, 3º, 4º a 7º (colaboração premiada), 8º (ação controlada), 10 a 14 (infiltração) e 19 a 21.',
    al: ['<b>A Lei 15.358/2026 NÃO revogou este diploma.</b> Instituiu regime especial aplicável em conjunto. Cuidado com a distinção: organização criminosa exige <b>4 ou mais pessoas</b>; a facção ultraviolenta da Lei 15.358 exige <b>3 ou mais</b>.'],
    lk: 'https://www.planalto.gov.br/ccivil_03/_ato2011-2014/2013/lei/l12850.htm' },
  { id: 'l8069', n: 'Lei 8.069/1990', nome: 'Estatuto da Criança e do Adolescente', m: 'extrav',
    em: 'Dispõe sobre a proteção integral à criança e ao adolescente.',
    esc: 'Arts. 103 a 128 (prática de ato infracional), 171 a 190 (apuração de ato infracional) e 225 a 244-B (crimes em espécie).', al: [],
    lk: 'https://www.planalto.gov.br/ccivil_03/leis/l8069.htm' },
  { id: 'l10741', n: 'Lei 10.741/2003', nome: 'Estatuto da Pessoa Idosa', m: 'extrav',
    em: 'Dispõe sobre o Estatuto da Pessoa Idosa.',
    esc: 'Arts. 43 a 45 (medidas de proteção), 69 a 71 (acesso à justiça) e 93 a 108 (crimes em espécie).', al: [],
    lk: 'https://www.planalto.gov.br/ccivil_03/leis/2003/l10.741.htm' },
  { id: 'l7492', n: 'Lei 7.492/1986', nome: 'Crimes contra o Sistema Financeiro Nacional', m: 'extrav',
    em: 'Define os crimes contra o sistema financeiro nacional.',
    esc: 'Texto integral. Destaque para os arts. 1º, 2º, 4º, 5º, 6º, 16, 22 e 26.', al: [],
    lk: 'https://www.planalto.gov.br/ccivil_03/leis/l7492.htm' },
  { id: 'l4737', n: 'Lei 4.737/1965', nome: 'Código Eleitoral — disposições penais', m: 'extrav',
    em: 'Institui o Código Eleitoral.',
    esc: "Somente a Parte Quinta, 'Disposições Penais' — arts. 283 a 364.",
    al: ['<b>Lei 15.358/2026:</b> alterou o art. 71 (suspensão de direitos políticos).'],
    lk: 'https://www.planalto.gov.br/ccivil_03/leis/l4737.htm' },
  { id: 'l7210', n: 'Lei 7.210/1984', nome: 'Lei de Execução Penal', m: 'extrav',
    em: 'Institui a Lei de Execução Penal.',
    esc: 'Arts. 38 a 43 (direitos e deveres do preso), 44 a 60 (disciplina, faltas graves e RDD), 110 a 119 (regimes e progressão), 126 a 130 (remição) e 131 a 146 (livramento condicional).',
    al: ["<b>Lei 15.402/2026</b> (promulgada em 08/05/2026 após rejeição de veto): alterou o caput e os incisos do <b>art. 112</b>, criando novos percentuais de progressão (70%, 75%, 80% e 85%), e inseriu o §9º ao art. 126 (remição em regime domiciliar). O feminicídio primário passou à alínea 'd' do inciso VI (75%), com o inciso VI-A revogado.",
      '<b>Lei 15.358/2026:</b> inseriu os arts. 41-A e 41-B (monitoramento audiovisual de visitas e, mediante autorização judicial em caso de conluio, da comunicação com o advogado) e alterou os arts. 52 (RDD), 86 e 112.',
      'Estude o art. 112 pela redação de 2026: reproduzir os percentuais antigos é o erro mais comum.'],
    lk: 'https://www.planalto.gov.br/ccivil_03/leis/l7210.htm' },
  { id: 'l8137', n: 'Lei 8.137/1990', nome: 'Crimes contra a ordem tributária, econômica e as relações de consumo', m: 'extrav',
    em: 'Define crimes contra a ordem tributária, econômica e contra as relações de consumo.',
    esc: 'Texto integral. Destaque para os arts. 1º, 2º, 3º, 4º, 7º e 16.',
    al: ['<b>Súmula Vinculante 24:</b> não se tipifica crime material contra a ordem tributária (art. 1º, I a IV) antes do lançamento definitivo do tributo.'],
    lk: 'https://www.planalto.gov.br/ccivil_03/leis/l8137.htm' },
  { id: 'l8078', n: 'Lei 8.078/1990', nome: 'Código de Defesa do Consumidor — infrações penais', m: 'extrav',
    em: 'Dispõe sobre a proteção do consumidor.',
    esc: "Somente o Título II, 'Das Infrações Penais' — arts. 61 a 80.", al: [],
    lk: 'https://www.planalto.gov.br/ccivil_03/leis/l8078compilado.htm' },
  { id: 'l8429', n: 'Lei 8.429/1992', nome: 'Lei de Improbidade Administrativa', m: 'adm',
    em: 'Dispõe sobre as sanções aplicáveis por atos de improbidade administrativa.',
    esc: 'Texto integral, na redação da Lei 14.230/2021. Destaque para os arts. 1º, 9º, 10, 11, 12, 17, 17-B, 21 e 23.',
    al: ['<b>Lei 14.230/2021:</b> exige <b>dolo</b> em todas as modalidades, extinguindo a improbidade culposa; o rol do art. 11 passou a ser <b>taxativo</b>.',
      '<b>STF, Tema 1199 (ARE 843.989):</b> a revogação da modalidade culposa é irretroativa quanto à coisa julgada e à execução, mas a nova lei incide sobre atos culposos ainda sem condenação transitada em julgado; os novos prazos prescricionais não retroagem.'],
    lk: 'https://www.planalto.gov.br/ccivil_03/leis/l8429.htm' },
  { id: 'dudh', n: 'Resolução 217-A (III)', nome: 'Declaração Universal dos Direitos Humanos (1948)', m: 'igual',
    em: 'Proclamada pela Assembleia Geral das Nações Unidas em 10 de dezembro de 1948.',
    esc: 'Texto integral — 30 artigos.', al: [],
    lk: 'https://www.un.org/pt/about-us/universal-declaration-of-human-rights' },
  { id: 'dl3688', n: 'DL 3.688/1941', nome: 'Lei das Contravenções Penais', m: 'extrav',
    em: 'Lei das Contravenções Penais.',
    esc: 'Texto integral. Destaque para os arts. 4º, 21, 42, 47, 50, 58, 59 e 65.',
    al: ['<b>Lei 14.994/2024:</b> inseriu o §2º no art. 21 — pena aplicada em triplo quando a vias de fato for praticada contra a mulher por razões da condição do sexo feminino.',
      'Não se pune a tentativa de contravenção (art. 4º).'],
    lk: 'https://www.planalto.gov.br/ccivil_03/decreto-lei/del3688.htm' },
  { id: 'l9613', n: 'Lei 9.613/1998', nome: 'Lei de Lavagem de Dinheiro', m: 'extrav',
    em: 'Dispõe sobre os crimes de lavagem ou ocultação de bens, direitos e valores.',
    esc: 'Texto integral. Destaque para os arts. 1º, 2º, 4º, 9º, 10, 11 e 17-B.',
    al: ['A Lei 12.683/2012 eliminou o rol taxativo de crimes antecedentes: basta infração penal antecedente.',
      '<b>STF, Tema 990:</b> é legítimo o compartilhamento de relatórios de inteligência financeira do COAF com a persecução penal, sem autorização judicial prévia.',
      '<b>Lei 15.358/2026:</b> alterou dispositivos — confira a redação vigente.'],
    lk: 'https://www.planalto.gov.br/ccivil_03/leis/l9613.htm' },
  { id: 'l12037', n: 'Lei 12.037/2009', nome: 'Lei de Identificação Criminal', m: 'proc',
    em: 'Dispõe sobre a identificação criminal do civilmente identificado.',
    esc: 'Texto integral — diploma curto. Destaque para os arts. 2º, 3º, 5º, 5º-A, 7º-A e 7º-C.', al: [],
    lk: 'https://www.planalto.gov.br/ccivil_03/_ato2007-2010/2009/lei/l12037.htm' },
  { id: 'l12830', n: 'Lei 12.830/2013', nome: 'Investigação criminal conduzida pelo delegado de polícia', m: 'proc',
    em: 'Dispõe sobre a investigação criminal conduzida pelo delegado de polícia.',
    esc: 'Texto integral — apenas três artigos, de altíssima incidência.', al: [],
    lk: 'https://www.planalto.gov.br/ccivil_03/_ato2011-2014/2013/lei/l12830.htm' },
  { id: 'l9807', n: 'Lei 9.807/1999', nome: 'Proteção a vítimas e testemunhas', m: 'extrav',
    em: 'Organiza a proteção a vítimas e testemunhas ameaçadas e a réus colaboradores.',
    esc: 'Texto integral. Destaque para os arts. 1º, 2º, 7º, 8º, 13, 14 e 15.', al: [],
    lk: 'https://www.planalto.gov.br/ccivil_03/leis/l9807.htm' },
  { id: 'l14597', n: 'Lei 14.597/2023', nome: 'Lei Geral do Esporte — infrações penais', m: 'extrav',
    em: 'Institui a Lei Geral do Esporte.',
    esc: 'Somente as infrações penais: arts. 198 a 202 e o art. 165 (corrupção privada no esporte).',
    al: ['<b>Revogou o Estatuto do Torcedor (Lei 10.671/2003)</b>, inclusive os arts. 41-B a 41-G, migrando os tipos penais para os arts. 198 a 202.',
      'A Lei Pelé (9.615/1998) <b>não</b> foi integralmente revogada — a revogação total foi vetada.',
      'Confira no Planalto o texto exato dos §§ do art. 201 e do art. 202, que tratam de torcidas organizadas.'],
    lk: 'https://www.planalto.gov.br/ccivil_03/_ato2023-2026/2023/lei/l14597.htm' },
  { id: 'l13146', n: 'Lei 13.146/2015', nome: 'Estatuto da Pessoa com Deficiência', m: 'extrav',
    em: 'Institui a Lei Brasileira de Inclusão da Pessoa com Deficiência.',
    esc: 'Arts. 1º a 5º (conceitos), 79 a 83 (acesso à justiça) e 88 a 91 (crimes e infrações).', al: [],
    lk: 'https://www.planalto.gov.br/ccivil_03/_ato2015-2018/2015/lei/l13146.htm' },
  { id: 'l14344', n: 'Lei 14.344/2022', nome: 'Lei Henry Borel', m: 'extrav',
    em: 'Cria mecanismos de prevenção e enfrentamento da violência doméstica e familiar contra a criança e o adolescente.',
    esc: 'Texto integral. Destaque para os arts. 20, 21, 22, 25 e 28.',
    al: ['A pena do art. 25 (descumprimento de medida protetiva — detenção de 3 meses a 2 anos) <b>não</b> acompanhou a elevação promovida na Lei Maria da Penha pela Lei 14.994/2024. Cuidado ao comparar.'],
    lk: 'https://www.planalto.gov.br/ccivil_03/_ato2019-2022/2022/lei/l14344.htm' },
  { id: 'l15358', n: 'Lei 15.358/2026', nome: 'Marco Legal de Combate ao Crime Organizado (Lei Antifacção)', m: 'extrav',
    em: 'Estabelece o marco legal de combate ao crime organizado no Brasil.',
    esc: 'Texto integral. É a lei mais nova do edital e a de maior probabilidade de cobrança literal.',
    al: ['Publicada no DOU em <b>25/03/2026</b>, com vigência imediata. O art. 43 foi vetado.',
      'Cria o crime de <b>domínio social estruturado</b> (art. 2º — reclusão de 20 a 40 anos) e o de <b>favorecimento ao domínio social estruturado</b> (art. 3º — reclusão de 12 a 20 anos e multa). Todos são hediondos.',
      'Define <b>organização criminosa ultraviolenta (facção)</b> como agrupamento de <b>3 ou mais pessoas</b> que emprega violência, grave ameaça ou coação para impor controle territorial ou social — não confundir com as 4 ou mais pessoas da Lei 12.850/2013.',
      'Prazos de inquérito: 90 dias com indiciado preso e 270 dias com solto, prorrogáveis.',
      'Alterou o CP, o CPP, a LEP, a Lei dos Crimes Hediondos, a Lei de Drogas, o Estatuto do Desarmamento, a Lei de Lavagem e o Código Eleitoral.'],
    lk: 'https://www.planalto.gov.br/ccivil_03/_ato2023-2026/2026/lei/l15358.htm' },

  /* ===== DIREITO ADMINISTRATIVO ===== */
  { id: 'l14133', n: 'Lei 14.133/2021', nome: 'Lei de Licitações e Contratos Administrativos', m: 'adm',
    em: 'Estabelece normas gerais de licitação e contratação para as Administrações Públicas.',
    esc: 'Artigos essenciais: 5º (princípios), 6º (definições), 17, 28 (modalidades), 29 a 32, 33 (critérios de julgamento), 74 (inexigibilidade) e 75 (dispensa). Os crimes remetem aos arts. 337-E a 337-P do CP.',
    al: ['Extinguiu as modalidades convite e tomada de preços; criou o diálogo competitivo.'],
    lk: 'https://www.planalto.gov.br/ccivil_03/_ato2019-2022/2021/lei/l14133.htm' },

  /* ===== LEGISLAÇÃO GERAL E ESTADUAL ===== */
  { id: 'ba6677', n: 'Lei BA 6.677/1994', nome: 'Estatuto do Servidor Público Civil do Estado da Bahia', m: 'geral',
    em: 'Dispõe sobre o Estatuto dos Servidores Públicos Civis do Estado da Bahia.',
    esc: 'Capítulos de provimento e vacância, direitos e vantagens, deveres, proibições, responsabilidades, penalidades e processo administrativo disciplinar.', al: [],
    lk: 'https://www.legislabahia.ba.gov.br/documentos/lei-no-6677-de-26-de-setembro-de-1994' },
  { id: 'ba11370', n: 'Lei BA 11.370/2009', nome: 'Lei Orgânica da Polícia Civil do Estado da Bahia', m: 'geral',
    em: 'Dispõe sobre a Lei Orgânica da Polícia Civil do Estado da Bahia.',
    esc: 'Texto integral. Atenção às atribuições das carreiras: Delegado (art. 50), Escrivão (art. 51) e <b>Investigador (art. 52)</b>.',
    al: ['O art. 4º recebeu redação da Lei 14.580/2023.',
      'O §1º do art. 50 dispõe que se considera autoridade policial, <b>exclusivamente</b>, o ocupante da carreira de Delegado de Polícia Civil. Confira a redação vigente no LegislaBahia — há versões divergentes circulando em bancos de questões.'],
    lk: 'https://www.legislabahia.ba.gov.br/documentos/lei-no-11370-de-04-de-fevereiro-de-2009' },
  { id: 'ba14634', n: 'Lei BA 14.634/2023', nome: 'Licitações e contratos administrativos do Estado da Bahia', m: 'geral',
    em: 'Normas de licitações e contratos administrativos aplicáveis no âmbito do Estado da Bahia.',
    esc: 'Artigos essenciais. Aplica subsidiariamente a Lei federal 14.133/2021 (art. 2º).',
    al: ['Publicada em 28/11/2023; regulamentada pelo Decreto estadual 23.059/2024.'],
    lk: 'https://www.legislabahia.ba.gov.br/documentos/lei-no-14634-de-28-de-novembro-de-2023' },
  { id: 'ba12209', n: 'Lei BA 12.209/2011', nome: 'Processo administrativo no Estado da Bahia', m: 'geral',
    em: 'Dispõe sobre o processo administrativo no âmbito da Administração do Estado da Bahia.',
    esc: 'Artigos essenciais: 1º, 3º (princípios), 12 (prazo para atos), 39 (decadência para anular — 5 anos), 45 (prazo para decidir — 30 dias) e 46.', al: [],
    lk: 'https://www.legislabahia.ba.gov.br/documentos/lei-no-12209-de-20-de-abril-de-2011' },
  { id: 'l8906', n: 'Lei 8.906/1994', nome: 'Estatuto da Advocacia e da OAB', m: 'geral',
    em: 'Dispõe sobre o Estatuto da Advocacia e a Ordem dos Advogados do Brasil.',
    esc: 'Arts. 6º a 7º-B (direitos e prerrogativas) e 34 a 43 (infrações e sanções disciplinares).',
    al: ['As prerrogativas do art. 7º dialogam com a Súmula Vinculante 14 e com o art. 32 da Lei de Abuso de Autoridade.'],
    lk: 'https://www.planalto.gov.br/ccivil_03/leis/l8906.htm' },

  /* ===== PROMOÇÃO DA IGUALDADE RACIAL E DE GÊNERO ===== */
  { id: 'cebahia', n: 'Const. BA — Cap. XXIII', nome: "Constituição do Estado da Bahia — 'Do Negro'", m: 'igual',
    em: 'Capítulo XXIII da Constituição do Estado da Bahia (arts. 286 a 290).',
    esc: 'Texto integral do capítulo — apenas cinco artigos, de cobrança quase certa.',
    al: ['O art. 290 fixa o dia <b>20 de novembro</b> como Dia da Consciência Negra.',
      'O art. 287 veda ao Estado manter relações com países de política oficial de discriminação racial.'],
    lk: 'https://www.legislabahia.ba.gov.br/documentos/constituicao-do-estado-da-bahia' },
  { id: 'l12288', n: 'Lei 12.288/2010', nome: 'Estatuto da Igualdade Racial', m: 'igual',
    em: 'Institui o Estatuto da Igualdade Racial.',
    esc: 'Texto integral. Destaque para o art. 1º, parágrafo único (definições de discriminação racial, desigualdade de gênero e raça, população negra e ações afirmativas).', al: [],
    lk: 'https://www.planalto.gov.br/ccivil_03/_ato2007-2010/2010/lei/l12288.htm' },
  { id: 'ba13182', n: 'Lei BA 13.182/2014', nome: 'Estatuto da Igualdade Racial e de Combate à Intolerância Religiosa da Bahia', m: 'igual',
    em: 'Institui o Estatuto Estadual da Igualdade Racial e de Combate à Intolerância Religiosa.',
    esc: 'Texto integral. Destaque para o <b>art. 49</b>, que reserva 30% das vagas em concursos estaduais à população negra — é o fundamento da reserva deste próprio edital.',
    al: ['Publicada em 06/06/2014. O percentual estadual de 30% é superior aos 20% da Lei federal 12.990/2014.'],
    lk: 'https://www.legislabahia.ba.gov.br/documentos/lei-no-13182-de-06-de-junho-de-2014' },
  { id: 'ba14521', n: 'Lei BA 14.521/2022', nome: 'Estrutura da SEPROMI e da Administração estadual', m: 'igual',
    em: 'Dispõe sobre a Secretaria de Promoção da Igualdade Racial e dos Povos e Comunidades Tradicionais.',
    esc: 'Artigos relativos à SEPROMI e suas competências.',
    al: ['Se o link não abrir diretamente, busque pelo número 14.521 no portal LegislaBahia.'],
    lk: 'https://www.legislabahia.ba.gov.br/' },
  { id: 'd65810', n: 'Decreto 65.810/1969', nome: 'Convenção sobre eliminação da discriminação racial', m: 'igual',
    em: 'Promulga a Convenção Internacional sobre a Eliminação de todas as Formas de Discriminação Racial.',
    esc: 'Texto integral da Convenção.', al: [],
    lk: 'https://www.planalto.gov.br/ccivil_03/decreto/1950-1969/d65810.html' },
  { id: 'd4377', n: 'Decreto 4.377/2002', nome: 'Convenção sobre eliminação da discriminação contra a mulher (CEDAW)', m: 'igual',
    em: 'Promulga a Convenção sobre a Eliminação de Todas as Formas de Discriminação contra a Mulher.',
    esc: 'Texto integral da Convenção.', al: [],
    lk: 'https://www.planalto.gov.br/ccivil_03/decreto/2002/d4377.htm' },
  { id: 'l2889', n: 'Lei 2.889/1956', nome: 'Crime de Genocídio', m: 'igual',
    em: 'Define e pune o crime de genocídio.',
    esc: 'Texto integral — apenas seis artigos.', al: [],
    lk: 'https://www.planalto.gov.br/ccivil_03/leis/l2889.htm' },
  { id: 'l7437', n: 'Lei 7.437/1985', nome: 'Lei Caó', m: 'igual',
    em: 'Inclui entre as contravenções penais a prática de atos resultantes de preconceito.',
    esc: 'Texto integral — diploma curto.', al: [],
    lk: 'https://www.planalto.gov.br/ccivil_03/leis/l7437.htm' },
  { id: 'l10678', n: 'Lei 10.678/2003', nome: 'Criação da Secretaria de Políticas de Promoção da Igualdade Racial', m: 'igual',
    em: 'Cria a Secretaria Especial de Políticas de Promoção da Igualdade Racial da Presidência da República.',
    esc: 'Texto integral e alterações posteriores.', al: [],
    lk: 'https://www.planalto.gov.br/ccivil_03/leis/2003/l10.678.htm' },
  { id: 'l13341', n: 'Lei 13.341/2016', nome: 'Organização da Presidência e dos Ministérios', m: 'igual',
    em: 'Altera a organização básica dos órgãos da Presidência da República e dos Ministérios.',
    esc: 'Artigos relativos à estrutura de promoção da igualdade racial.', al: [],
    lk: 'https://www.planalto.gov.br/ccivil_03/_ato2015-2018/2016/lei/l13341.htm' },
  { id: 'l14600', n: 'Lei 14.600/2023', nome: 'Organização básica da Presidência e dos Ministérios', m: 'igual',
    em: 'Estabelece a organização básica dos órgãos da Presidência da República e dos Ministérios.',
    esc: 'Artigos relativos ao Ministério da Igualdade Racial.', al: [],
    lk: 'https://www.planalto.gov.br/ccivil_03/_ato2023-2026/2023/lei/l14600.htm' },
  { id: 'd4886', n: 'Decreto 4.886/2003', nome: 'Política Nacional de Promoção da Igualdade Racial', m: 'igual',
    em: 'Institui a Política Nacional de Promoção da Igualdade Racial — PNPIR.',
    esc: 'Texto integral.', al: [],
    lk: 'https://www.planalto.gov.br/ccivil_03/decreto/2003/d4886.htm' },
]
